name: api-qasim

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set Git identity for version bump commit
      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Remove the existing Git tag if it exists
      - name: Delete existing Git tag (if exists)
        run: |
          git tag -d v$(node -p "require('./package.json').version") || true
          git push --delete origin v$(node -p "require('./package.json').version") || true

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Bump package version
      - name: Set package version
        run: npm version patch

      # Publish to npm with authentication token
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          
